DATALOADER:
  batch_size: 16
  num_workers: 0
EXP:
  DATASET: modelnet40_c
  EXP_ID: c_ptv1_run_1
  LOSS_NAME: smooth
  MODEL_NAME: ptv1
  SEED: 1
  TASK: cls
TRAIN:
  l2: 0.0
ADAPT:
  METHOD: tent
  ITER: 10